### ISSUE TITLE
BasicFrameworkModel - Abstract override error

### ISSUE THREAD

**Issue by markomirtic** [ConvergentThinker/auto_test_ui#7]
/Users/Microsoft/auto_test_ui/src/test/java/org/autotestui/model/BasicFrameworkModel.java:14:9
java: org.autotestui.model.BasicFrameworkModel is not abstract and does not override abstract method getScenario() in org.autotestui.interfaces.ScenarioModel

**Comment by ConvergentThinker** [comment]
Hi @markomirtic , I request you to read more about @Data from Lombok lib. @Data will create getters and setters for you. 
hence we do not need to specify  getScenario() in BasicFrameworkModel.java.
